// <auto-generated />
using System;
using DigitalArsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalArsApi.Migrations
{
    [DbContext(typeof(DigitalArsContext))]
    [Migration("20250519003056_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("DigitalArsApi.Models.Cuenta", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DNI")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("F_Update")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.HasKey("Numero");

                    b.HasIndex("DNI");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("DigitalArsApi.Models.EstadoPlazoFijo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadosPlazoFijo");
                });

            modelBuilder.Entity("DigitalArsApi.Models.PlazoFijo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("F_Fin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("F_Inicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEstado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTransaccion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("InteresEsperado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TNA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTransaccion")
                        .IsUnique();

                    b.ToTable("PlazosFijos");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CtaDestino")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CtaOrigen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CtaDestino");

                    b.HasIndex("CtaOrigen");

                    b.HasIndex("IdTipo");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Usuario", b =>
                {
                    b.Property<int>("DNI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("F_Update")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DNI");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RolesUsuarios", b =>
                {
                    b.Property<int>("DNI")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("DNI", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("RolesUsuarios");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Cuenta", b =>
                {
                    b.HasOne("DigitalArsApi.Models.Usuario", "Usuario")
                        .WithMany("Cuentas")
                        .HasForeignKey("DNI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DigitalArsApi.Models.PlazoFijo", b =>
                {
                    b.HasOne("DigitalArsApi.Models.EstadoPlazoFijo", "Estado")
                        .WithMany("PlazosFijos")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalArsApi.Models.Transaccion", "Transaccion")
                        .WithOne("PlazoFijo")
                        .HasForeignKey("DigitalArsApi.Models.PlazoFijo", "IdTransaccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Transaccion", b =>
                {
                    b.HasOne("DigitalArsApi.Models.Cuenta", "CuentaDestino")
                        .WithMany("TransaccionesDestino")
                        .HasForeignKey("CtaDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalArsApi.Models.Cuenta", "CuentaOrigen")
                        .WithMany("TransaccionesOrigen")
                        .HasForeignKey("CtaOrigen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalArsApi.Models.Tipo", "Tipo")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuentaDestino");

                    b.Navigation("CuentaOrigen");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("RolesUsuarios", b =>
                {
                    b.HasOne("DigitalArsApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DNI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolesUsuarios_Usuarios");

                    b.HasOne("DigitalArsApi.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolesUsuarios_Roles");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Cuenta", b =>
                {
                    b.Navigation("TransaccionesDestino");

                    b.Navigation("TransaccionesOrigen");
                });

            modelBuilder.Entity("DigitalArsApi.Models.EstadoPlazoFijo", b =>
                {
                    b.Navigation("PlazosFijos");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Tipo", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Transaccion", b =>
                {
                    b.Navigation("PlazoFijo");
                });

            modelBuilder.Entity("DigitalArsApi.Models.Usuario", b =>
                {
                    b.Navigation("Cuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
